import React from "react";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import NavBarSignedIn from "../../../../components/NavbarSignedIn";
import MobileBottomNav from "../../../../components/MobileBottomNav";
import Section4Card from "../../../../components/Section4Card";
import Typography from "@mui/material/Typography";
import Paper from "@mui/material/Paper";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TablePagination from "@mui/material/TablePagination";
import TableRow from "@mui/material/TableRow";
import IconButton from "@mui/material/IconButton";
import DeleteIcon from "@mui/icons-material/Delete";
import EditIcon from "@mui/icons-material/Edit";

const Fields = [
  "Year",
  "Nickname",
  "Kind of Activity",
  "Scope",
  "Level",
  "",
  "",
];

const Entries = [
  {
    ID: "111",
    Nickname: "Fall Term Capstone",
    Year: "Sept 2024 - Dec 2024",
    ActivityKind: "Coursework",
    Scope: "PWA",
    Level: "Beginner",
  },
  {
    ID: "222",
    Nickname: "Winter Term Capstone",
    Year: "Jan 2025 - March 2024",
    ActivityKind: "Coursework",
    Scope: "PWA",
    Level: "Beginner",
  },
  {
    ID: "333",
    Nickname: "Spring Term Capstone",
    Year: "April 2025 - June 2025",
    ActivityKind: "Coursework",
    Scope: "PWA",
    Level: "Beginner",
  },
];

const StyledTableRow = styled(TableRow)(({}) => ({
  "&:nth-of-type(odd)": {
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  "&:nth-of-type(even)": {
    backgroundColor: "rgba(255,255,255,0.85)",
  },
  "&:nth-of-type(odd):hover": {
    backgroundColor: "rgba(255,255,255,0.98)",
  },
  "&:nth-of-type(even):hover": {
    backgroundColor: "rgba(255,255,255,0.98)",
  },
  // hide last border
  "&:last-child td, &:last-child th": {
    border: 0,
  },
}));

function Section() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <NavBarSignedIn />

      <Box
        sx={(theme) => ({
          [theme.breakpoints.up("xs")]: { height: "20px" },
          [theme.breakpoints.up("sm")]: { height: "25px" },
          [theme.breakpoints.up("md")]: { height: "30px" },
          [theme.breakpoints.up("lg")]: { height: "35px" },
          [theme.breakpoints.up("xl")]: { height: "40px" },
        })}
      ></Box>
      <Typography
        variant="h4"
        sx={{
          display: { xs: "none", md: "block" },
          Width: "100%",
          textAlign: "center",
          fontWeight: "bold",
        }}
      >
        Section 3: Participation in 4-H Activities/Events
      </Typography>
      <Paper
        sx={{
          width: "90%",
          overflow: "hidden",
          display: { xs: "none", md: "flex" },
          marginLeft: "5%",
          marginRight: "5%",
          marginTop: "15px",
        }}
      >
        <TableContainer sx={{ maxHeight: 440 }}>
          <Table stickyHeader aria-label="sticky table">
            <TableHead>
              <TableRow>
                {Fields.map((item, index) => (
                  <TableCell
                    key={index}
                    align="right"
                    style={{ minWidth: 0.5 / Fields.length }}
                    sx={{ textAlign: "center" }}
                  >
                    {item}
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {Entries.map((item, index) => (
                <StyledTableRow hover role="checkbox" tabIndex={-1} key={index}>
                  <TableCell sx={{ textAlign: "center" }}>
                    {item.Year}
                  </TableCell>
                  <TableCell sx={{ textAlign: "center" }}>
                    {item.Nickname}
                  </TableCell>
                  <TableCell sx={{ textAlign: "center" }}>
                    {item.ActivityKind}
                  </TableCell>
                  <TableCell sx={{ textAlign: "center" }}>
                    {item.Scope}
                  </TableCell>
                  <TableCell sx={{ textAlign: "center" }}>
                    {item.Level}
                  </TableCell>
                  <TableCell>
                    <IconButton>
                      <EditIcon />
                    </IconButton>
                  </TableCell>
                  <TableCell>
                    <IconButton>
                      <DeleteIcon />
                    </IconButton>
                  </TableCell>
                </StyledTableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
      <Box
        sx={{
          flexGrow: 1,
          display: { xs: "flex", md: "none" },
          width: "100%",
          flexDirection: "column",
          paddingBottom: "50px",
        }}
      >
        {Entries.map((item, index) => (
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "80%",
              paddingLeft: "10%",
              paddingRight: "10%",
              paddingBottom: "20px",
            }}
          >
            <Section4Card
              ID={item.ID}
              Nickname={item.Nickname}
              Year={item.Year}
              ActivityKind={item.ActivityKind}
              Scope={item.Scope}
              Level={item.Level}
            />
          </Box>
        ))}
      </Box>
      <MobileBottomNav />
    </Box>
  );
}

export default Section;
