"use client";

import React, { useState, useEffect } from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";

export default function Account() {
  const { currNavbarValues, updateFunction } = useNavbar();
  const { updateBookmarks } = useBookmark();

  useEffect(() => {
    var navbarContextPageValues: NavbarValues = {
      mobileTitle: "Account",
      desktopTitle: "4-H Record Books",
      hrefTitle: "/Dashboard",
      mobileTopIcon: "none",
      NavbarLinks: navbarAppLinks,
    };
    updateFunction(navbarContextPageValues);

    // toggle to trigger bookmarks icon to check if page is bookmarked
    updateBookmarks(true);
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Box>
        <Typography
          variant="h4"
          sx={{
            display: { xs: "none", md: "block" },
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          {currNavbarValues.mobileTitle}
        </Typography>
      </Box>
    </Box>
  );
}
