"use client";

import React, { useEffect, useRef } from "react";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import MenuOfLinks from "@/components/MenuOfLinks";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";

export default function Account() {
  const { updateFunction } = useNavbar();
  const { updateBookmarks } = useBookmark();
  const hasRun = useRef(false);

  useEffect(() => {
    if (!hasRun.current) {
      const navbarContextPageValues: NavbarValues = {
        mobileTitle: "Account",
        desktopTitle: "My Account",
        hrefTitle: "/Dashboard",
        mobileTopIcon: "none",
        NavbarLinks: navbarAppLinks,
      };
      updateFunction(navbarContextPageValues);

      // toggle to trigger bookmarks icon to check if page is bookmarked
      updateBookmarks(true);

      hasRun.current = true;
    }
  });

  const linkButtonData: [string, string][] = [["/auth/logout", "Sign Out"]];

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <MenuOfLinks array={linkButtonData} menuTitle="Account" />
            </Box>
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <MenuOfLinks array={[]} menuTitle="General" />
            </Box>
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              flex: 1,
              position: "relative",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <MenuOfLinks array={linkButtonData} menuTitle="Account" />
          </Box>
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "40%",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <MenuOfLinks array={[]} menuTitle="General" />
          </Box>
        </Box>
      </Toolbar>
    </Box>
  );
}
