// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";

interface ResumeMenuProps {
  category: string;
  section_number_1: string;
  section_number_2: string;
  section_description_1: string;
  section_description_2: string;
}

function ResumeMenus({
  category,
  section_number_1,
  section_number_2,
  section_description_1,
  section_description_2,
}: ResumeMenuProps) {
  const href1 = "/Dashboard/Resume/Section/" + section_number_1;
  const href2 = "/Dashboard/Resume/Section/" + section_number_2;

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250 }} component={Paper}>
      <Table sx={{ minWidth: 250 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                {category}
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell>
              <Button
                style={{
                  width: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href={href1}
              >
                Section {section_number_1}: 4-H {section_description_1}
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell>
              <Button
                style={{
                  width: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href={href2}
              >
                Section {section_number_2}: {section_description_2}
              </Button>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default ResumeMenus;
