"use client";

import React, { useState, useEffect, useRef } from "react";
import { getAccessToken } from "@auth0/nextjs-auth0";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";
import { useProject } from "@/context/ProjectContext";
import { Project, fetchAllProjects } from "@/API/ProjectAPI";
import PreviewCard from "@/components/Projects/PreviewCard";
import { usePathname } from "next/navigation";

function Dashboard() {
  const pathname = usePathname();
  const { updateFunction } = useNavbar();
  const { updateBookmarks } = useBookmark();
  const { updateProjects, currProjectValues, populated } = useProject();
  const [accessToken, setAccessToken] = useState("");
  const [allProjects, setAllProjects] = useState<Project[]>(currProjectValues);
  const setProjects = (Projects: Project[]) => {
    setAllProjects(Projects);
    updateProjects(Projects);
  };
  const hasRun1 = useRef(false);
  const hasRun2 = useRef(false);

  // get auth0 jwt and projects
  useEffect(() => {
    if (!hasRun1.current) {
      const navbarContextPageValues: NavbarValues = {
        mobileTitle: "Projects",
        desktopTitle: "This Year's Projects",
        hrefTitle: "/Dashboard",
        mobileTopIcon: "none",
        NavbarLinks: navbarAppLinks,
      };
      updateFunction(navbarContextPageValues);

      // toggle to trigger bookmarks icon to check if page is bookmarked
      updateBookmarks(true);
      hasRun1.current = true;
    }

    if (!hasRun2.current) {
      const getProjectData = async () => {
        try {
          console.log("data exsists for projects?", populated);
          if (!populated) {
            if (accessToken == "") {
              const token = await getAccessToken();
              setAccessToken(token);
              const projectData = await fetchAllProjects(token);
              setProjects(projectData);
            } else {
              const projectData = await fetchAllProjects(accessToken);
              setProjects(projectData);
            }
          }
        } catch (error) {
          console.error(error);
        }
      };
      getProjectData();
      hasRun2.current = true;
    }
  });

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box
      className="App"
      sx={{
        width: "90%",
        marginLeft: "5%",
        marginRight: "5%",
        display: "flex",
        flexDirection: "row",
      }}
    >
      <Box
        sx={{
          flexGrow: 1,
          display: { xs: "flex", md: "none" },
          width: "100%",
          flexDirection: "column",
          paddingBottom: "50px",
        }}
      >
        {allProjects &&
          allProjects.length > 0 &&
          allProjects.map((item, index) => (
            <PreviewCard
              key={index}
              project={item}
              path={pathname + "/" + item.type + "/" + item.id}
            />
          ))}
      </Box>
      <Box
        sx={{
          width: "100%",
          display: { xs: "none", md: "block" },
          marginLeft: "5%",
          marginRight: "5%",
          marginTop: "15px",
        }}
      >
        <Grid
          container
          rowSpacing={1}
          columnSpacing={0}
          sx={{
            width: "100%",
          }}
        >
          {allProjects &&
            allProjects.length > 0 &&
            allProjects.map((item, index) => (
              <Grid size={4} key={index}>
                <PreviewCard
                  project={item}
                  path={pathname + "/" + item.type + "/" + item.id}
                />
              </Grid>
            ))}
        </Grid>
      </Box>
    </Box>
  );
}

export default Dashboard;
