// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import LinkMenuRow from "@/components/LinkMenuRow";

interface ResumeMenuProps {
  category: string;
  section_number_1: string;
  section_number_2: string;
  section_description_1: string;
  section_description_2: string;
}

function ResumeMenus({
  category,
  section_number_1,
  section_number_2,
  section_description_1,
  section_description_2,
}: ResumeMenuProps) {
  const href1 = "/Dashboard/Resume/Section/" + section_number_1;
  const href2 = "/Dashboard/Resume/Section/" + section_number_2;
  const href1string =
    "Section " + section_number_1 + ": " + section_description_1;
  const href2string =
    "Section " + section_number_2 + ": " + section_description_2;
  const falseboo: boolean = false;

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250 }} component={Paper}>
      <Table sx={{ minWidth: 250 }} aria-label="simple table">
        <TableHead>
          <TableRow
            sx={{
              height: "4em",
              margin: "0px",
              padding: "0px",
            }}
          >
            <TableCell
              sx={{
                margin: "0px",
                paddingTop: "0px",
                padding: "0px",
              }}
            >
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                {category}
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <LinkMenuRow
            hrefOrFunction={href1}
            label={href1string}
            externalLink={falseboo}
          />
          <LinkMenuRow
            hrefOrFunction={href2}
            label={href2string}
            externalLink={falseboo}
            key={2}
          />
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default ResumeMenus;
