"use client";

import React, { useEffect, useRef, useState } from "react";
import { getAccessToken } from "@auth0/nextjs-auth0";
import Box from "@mui/material/Box";
import Modal from "@mui/material/Modal";
import Toolbar from "@mui/material/Toolbar";
import MenuOfSections from "@/components/Resume/MenuOfSections";
import { Button } from "@mui/material";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";
import sectionOutline from "@/components/Resume/SectionOutline.json";
import PDFPreviewModel from "@/components/Models/PDFPreviewModel";
import PDFFile from "@/components/Reports/Resume/Resume";
import { PDFDownloadButton } from "@/components/PDFDownloadButton";
import { getUser, User } from "@/API/UserAPI";
import { fetchResume } from "@/API/ResumeAPI";
import { useResume } from "@/context/ResumeContext";

const SectionsData = [
  {
    category: "Involvement Summary",
    section_number_1: "1",
    section_number_2: "2",
    section_description_1: sectionOutline.section1.title,
    section_description_2: sectionOutline.section2.title,
  },
  {
    category: "Participation",
    section_number_1: "3",
    section_number_2: "4",
    section_description_1: sectionOutline.section3.title,
    section_description_2: sectionOutline.section4.title,
  },
  {
    category: "Leadership",
    section_number_1: "5",
    section_number_2: "6",
    section_description_1: sectionOutline.section5.title,
    section_description_2: sectionOutline.section6.title,
  },
  {
    category: "Citizenship/Community Service",
    section_number_1: "7",
    section_number_2: "8",
    section_description_1: sectionOutline.section7.title,
    section_description_2: sectionOutline.section8.title,
  },
  {
    category: "Communications",
    section_number_1: "9",
    section_number_2: "10",
    section_description_1: sectionOutline.section9.title,
    section_description_2: sectionOutline.section10.title,
  },
  {
    category: "Contests/Competitions",
    section_number_1: "11",
    section_number_2: "12",
    section_description_1: sectionOutline.section11.title,
    section_description_2: sectionOutline.section12.title,
  },
  {
    category: "Recognitions",
    section_number_1: "13",
    section_number_2: "14",
    section_description_1: sectionOutline.section13.title,
    section_description_2: sectionOutline.section14.title,
  },
];

export default function Dashboard() {
  const { updateFunction } = useNavbar();
  const { updateBookmarks } = useBookmark();
  const hasRun = useRef(false);
  const hasRun2 = useRef(false);
  const [user, setUser] = useState<User>();
  const [showPreview, setShowPreview] = useState(false);
  const [accessToken, setAccessToken] = useState("");
  const { updateResume, Sections, SAll, SAllPopulated } = useResume();

  useEffect(() => {
    if (!hasRun.current) {
      hasRun.current = true;
      const navbarContextPageValues: NavbarValues = {
        mobileTitle: "Resume",
        desktopTitle: "My 4-H Resume",
        hrefTitle: "/Dashboard",
        NavbarLinks: navbarAppLinks,
      };
      updateFunction(navbarContextPageValues);

      // toggle to trigger bookmarks icon to check if page is bookmarked
      updateBookmarks(true);
    }
  }, [updateFunction, updateBookmarks]);

  // get user and resume data for resume preview/download
  useEffect(() => {
    if (!hasRun2.current) {
      hasRun2.current = true;

      const getData = async () => {
        try {
          if (accessToken == "") {
            const token = await getAccessToken();
            setAccessToken(token);

            const userData = await getUser(token);
            setUser(userData);

            const resumeData = await fetchResume(token);
            updateResume({ ResumeData: resumeData, section: "0" });
          } else {
            const userData = await getUser(accessToken);
            setUser(userData);

            const resumeData = await fetchResume(accessToken);
            updateResume({ ResumeData: resumeData, section: "0" });
          }
        } catch (error) {
          console.error(error);
        }
      };
      getData();
    }
  });

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Box
        sx={{
          width: "90%",
          marginLeft: "5%",
          marginRight: "5%",
          display: "flex",
          justifyContent: "center",

          flexDirection: "row",
        }}
      >
        {/* first box is placeholder for component that will have preview and download resume pdf */}
        <Button onClick={() => setShowPreview(true)}>Preview Resume</Button>
        {typeof user != "undefined" && SAllPopulated && (
          <PDFDownloadButton
            document={<PDFFile userData={user} resumeData={SAll} />}
            fileName={"My 4-H Resume.pdf"}
          />
        )}

        {showPreview && typeof user != "undefined" && SAllPopulated && (
          <Modal
            open={showPreview}
            onClose={() => setShowPreview(false)}
            aria-labelledby="preview-modal-title"
            aria-describedby="preview-modal-description"
          >
            <PDFPreviewModel handleClose={() => setShowPreview(false)}>
              <PDFFile userData={user} resumeData={SAll} />
            </PDFPreviewModel>
          </Modal>
        )}
        {/* CreateIconButton returns content in a simularly styled box */}
      </Box>
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            {SectionsData.map((item, index) => (
              <Box
                key={index}
                sx={{
                  flex: 1,
                  position: "relative",
                  padding: "20px",
                  Width: "80%",
                  paddingLeft: "10%",
                  paddingRight: "10%",
                  paddingBottom: "50px",
                }}
              >
                <MenuOfSections
                  category={item.category}
                  section_number_1={item.section_number_1}
                  section_number_2={item.section_number_2}
                  section_description_1={item.section_description_1}
                  section_description_2={item.section_description_2}
                />
              </Box>
            ))}
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
            flexWrap: "wrap",
            justifyContent: "center",
          }}
        >
          {SectionsData.map((item, index) => (
            <Box
              key={index}
              sx={{
                width: "29%",
                justifyContent: "center",
                paddingTop: "15px",
                paddingBottom: "15px",
                paddingLeft: "2%",
                paddingRight: "2%",
              }}
            >
              <MenuOfSections
                category={item.category}
                section_number_1={item.section_number_1}
                section_number_2={item.section_number_2}
                section_description_1={item.section_description_1}
                section_description_2={item.section_description_2}
              />
            </Box>
          ))}
        </Box>
      </Toolbar>
    </Box>
  );
}
