import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";
import Typography from "@mui/material/Typography";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Account() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarSignedIn />
      <div style={{ height: "85px" }}></div>
      <div>
        <Typography
          variant="h4"
          style={{
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          Account
        </Typography>
      </div>
    </div>
  );
}

export default Account;
