import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";
import Button from "@mui/material/Button";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import TextField from "@mui/material/TextField";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Auth() {
  const [typeAction, setTypeAction] = React.useState("Sign In");

  const handleChange = (event, updatedAction) => {
    setTypeAction(updatedAction);
  };

  const toggleChildren = [
    <ToggleButton value="Sign In" key="sign-in">
      Sign In
    </ToggleButton>,
    <ToggleButton value="Sign Up" key="sign-up">
      Sign Up
    </ToggleButton>,
  ];

  const control = {
    value: typeAction,
    onChange: handleChange,
    exclusive: true,
  };

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarSignedIn />
      <div style={{ height: "85px" }}></div>
      <div></div>
      <p
        style={{
          textAlign: "center",
        }}
      >
        <ToggleButtonGroup
          size="large"
          {...control}
          aria-label="Large sizes"
          style={{
            textAlign: "center",
          }}
        >
          {toggleChildren}
        </ToggleButtonGroup>
      </p>

      <Typography
        variant="h5"
        color="#339966"
        style={{
          Width: "100%",
          textAlign: "center",
          paddingBotton: "70px",
        }}
      >
        Welcome! {control.value} below.
      </Typography>

      <Box
        sx={{
          width: "50%",
          marginRight: "25%",
          marginLeft: "25%",
          flexWrap: "wrap",
          paddingBottom: "20px",
          paddingTop: "20px",
          justifyContent: "center",
        }}
      >
        <TextField
          sx={{ width: "100%" }}
          id="outlined-basic"
          label="Email"
          variant="outlined"
        />
        <TextField
          sx={{ width: "100%" }}
          id="outlined-basic"
          label="Password"
          variant="outlined"
        />
      </Box>
      <Button
        style={{
          width: "40%",
          marginRight: "30%",
          marginLeft: "30%",
        }}
        href="/Dashboard"
        variant="contained"
      >
        {control.value}
      </Button>
    </div>
  );
}

export default Auth;
