import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Dashboard() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarSignedIn />
      <div style={{ height: "75px" }}></div>
    </div>
  );
}

export default Dashboard;
