import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";

function Dashboard() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarSignedIn />
    </div>
  );
}

export default Dashboard;
