import React from "react";
import NavBarLanding from "../components/NavbarLanding";
import IntroBanner from "../components/IntroBanner";
import IntroAbout from "../components/IntroAbout";
import IntroTeam from "../components/IntroTeam";
import IntroContact from "../components/IntroContact";
import TableRow from "@mui/material/TableRow";
import TableCell from "@mui/material/TableCell";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Landing() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarLanding />
      <IntroBanner />
      <IntroAbout />
      <IntroTeam />
      <IntroContact />
    </div>
  );
}

export default Landing;
