import React from "react";
import NavBarLanding from "../components/NavbarLanding";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Landing() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarLanding />
    </div>
  );
}

export default Landing;
