import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";

function Projects() {
  //goes in body tag, per autogenerated index.html file in public folder
  <div className="App">
    <NavBarSignedIn />
  </div>;
}

export default Projects;
