import NavBarSignedIn from "../components/NavbarSignedIn";
import React, { useState, useEffect } from "react";
import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import Toolbar from "@mui/material/Toolbar";
import Box from "@mui/material/Box";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Projects() {
  // const [typeProjects, setTypeProjects] = React.useState("Current Projects");

  // const handleChange = (event, newTypeProjects) => {
  //   setTypeProjects(newTypeProjects);
  // };

  // const toggleChildren = [
  //   <ToggleButton
  //     value="All Projects"
  //     allDisplay="block"
  //     currentDisplay="none"
  //     key="all"
  //   >
  //     All Projects
  //   </ToggleButton>,
  //   <ToggleButton
  //     value="Current Project"
  //     allDisplay="none"
  //     currentDisplay="block"
  //     key="current"
  //   >
  //     Current Projects
  //   </ToggleButton>,
  // ];

  // const control = {
  //   value: typeProjects,
  //   allDisplay: typeProjects,
  //   currentDisplay: typeProjects,
  //   onChange: handleChange,
  //   exclusive: true,
  // };

  // // function to get current projects below

  // // fetch api function adapted from the following two resources:
  // // https://dev.to/antdp425/react-fetch-data-from-api-with-useeffect-27le
  // // https://www.pluralsight.com/resources/blog/guides/fetch-data-from-a-json-file-in-a-react-app
  // let [allCurrentProjects, setCurrentProjects] = useState(null);

  // // mock Postman server URL is as follows: https://7f5430c6-f0d3-4a3c-80e6-781aef7a7602.mock.pstmn.io
  // useEffect(() => {
  //   fetch("https://7f5430c6-f0d3-4a3c-80e6-781aef7a7602.mock.pstmn.io/projects")
  //     .then((response) => response.json())
  //     .then((data) => setCurrentProjects(data.CurrentProjects));
  // }, []);

  // function to get all projects below
  let [allProjects, setProjects] = useState(null);

  // mock Postman server URL is as follows: https://7f5430c6-f0d3-4a3c-80e6-781aef7a7602.mock.pstmn.io
  useEffect(() => {
    fetch("https://7f5430c6-f0d3-4a3c-80e6-781aef7a7602.mock.pstmn.io/project")
      .then((response) => response.json())
      .then((data) => setProjects(data.allProjects));
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <ThemeProvider theme={ColorTheme}>
      <div className="App">
        <NavBarSignedIn />
        <div style={{ height: "75px" }}></div>
        <Typography
          variant="h4"
          style={{
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
            marginBotton: "20px",
          }}
        >
          Projects
        </Typography>

        <p
          style={{
            textAlign: "center",
          }}
        >
          {/* <ToggleButtonGroup
            size="large"
            {...control}
            aria-label="Large sizes"
            style={{
              textAlign: "center",
            }}
          >
            {toggleChildren}
          </ToggleButtonGroup> */}
        </p>

        <Typography
          variant="h5"
          color="#339966"
          style={{
            Width: "100%",
            textAlign: "center",
            paddingBotton: "70px",
          }}
        >
          {/* Currently Showing {control.value} */}
          Currently Showing All Projects
        </Typography>

        <Toolbar
          disableGutters
          sx={{
            display: { xs: "flex" },
            flexDirection: "row",
            justifyContent: "space-between",
          }}
        >
          <Box
            sx={{
              flexGrow: 1,
              display: { xs: "flex", md: "none" },
              width: "100%",
            }}
          >
            <Box
              sx={{
                width: "100%",
              }}
            >
              {/* {allCurrentProjects &&
                allCurrentProjects.length > 0 &&
                allCurrentProjects.map((item) => (
                  <div
                    style={{
                      flex: 1,
                      position: "relative",
                      padding: "20px",
                      Width: "80%",
                      marginLeft: "10%",
                      marginRight: "10%",
                      marginBottom: "20px",
                      textAlign: "center",
                      backgroundColor: "#f7fbf9",
                    }}
                  >
                    <h3>{item.ProjectName}</h3>
                    <h4>({item.Year})</h4>
                  </div>
                ))} */}
              {allProjects &&
                allProjects.length > 0 &&
                allProjects.map((item) => (
                  <div
                    style={{
                      flex: 1,
                      position: "relative",
                      padding: "15px",
                      Width: "80%",
                      marginLeft: "10%",
                      marginRight: "10%",
                      marginBottom: "20px",
                      textAlign: "center",
                      backgroundColor: "#f7fbf9",
                    }}
                  >
                    <h3>{item.ProjectName}</h3>
                    <h4>({item.Year})</h4>
                  </div>
                ))}
            </Box>
          </Box>
          <Box
            sx={{
              flexGrow: 1,
              display: { xs: "none", md: "flex" },
              flexWrap: "wrap",
              width: "100%",
            }}
          >
            {/* {allCurrentProjects &&
              allCurrentProjects.length > 0 &&
              allCurrentProjects.map((item) => (
                <div
                  style={{
                    flex: 1,
                    position: "relative",
                    marginLeft: "5%",
                    marginRight: "5%",
                    marginTop: "15px",
                    textAlign: "center",
                    backgroundColor: "#f7fbf9",
                  }}
                >
                  <h3>{item.ProjectName}</h3>
                  <h4>({item.Year})</h4>
                </div>
              ))} */}

            {allProjects &&
              allProjects.length > 0 &&
              allProjects.map((item) => (
                <div
                  style={{
                    flex: 1,
                    position: "relative",
                    marginLeft: "5%",
                    marginRight: "5%",
                    marginTop: "15px",
                    padding: "15px",
                    minWidth: "30%",
                    maxWidth: "300px",
                    textAlign: "center",
                    backgroundColor: "#f7fbf9",
                  }}
                >
                  <h3>{item.ProjectName}</h3>
                  <h4>({item.Year})</h4>
                </div>
              ))}
          </Box>
        </Toolbar>
      </div>
    </ThemeProvider>
  );
}

export default Projects;
