import React from "react";
import NavBarSignedIn from "../components/NavbarSignedIn";
import { ThemeProvider } from "@mui/material/styles";
import ColorTheme from "../components/ColorTheme";

function Resume() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <div className="App">
      <NavBarSignedIn />
      <div style={{ height: "75px" }}></div>

      <h1>Note: To be implemented later. (12/3/2024)</h1>
    </div>
  );
}

export default Resume;
