"use client";

import React, { useEffect } from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";

function Dashboard() {
  const { currNavbarValues, updateFunction } = useNavbar();

  useEffect(() => {
    const navbarContextPageValues: NavbarValues = {
      mobileTitle: "Page Not Found",
      desktopTitle: "404: Page Not Found",
      hrefTitle: "/",
      mobileTopIcon: "none",
      NavbarLinks: navbarAppLinks,
    };

    updateFunction(navbarContextPageValues);
  });

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Box>
        <Typography
          variant="h4"
          sx={{
            display: { xs: "none", md: "block" },
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
            paddingTop: "20%",
          }}
        >
          {currNavbarValues.mobileTitle}
        </Typography>
      </Box>
    </Box>
  );
}

export default Dashboard;
