"use client";

import React, { useState, useEffect } from "react";
import ResourcesMenu from "@/components/Dashboard/ResourcesMenu";
import BookmarksMenu from "@/components/Dashboard/BookmarksMenu";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";

function Dashboard() {
  const { currNavbarValues, updateFunction } = useNavbar();

  useEffect(() => {
    var navbarContextPageValues: NavbarValues = {
      mobileTitle: "Section...",
      desktopTitle: "Section...",
      hrefTitle: "/",
      mobileTopIcon: "none",
      NavbarLinks: navbarAppLinks,
      Bookmarks: currNavbarValues.Bookmarks,
    };

    updateFunction(navbarContextPageValues);
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return <Box className="App"></Box>;
}

export default Dashboard;
