import React from "react";
import NavBarSignedIn from "../../components/NavbarSignedIn";
import MobileBottomNav from "../../components/MobileBottomNav";
import ResourcesMenu from "../../components/Dashboard/ResourcesMenu";
import BookmarksMenu from "../../components/Dashboard/BookmarksMenu";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";

function Dashboard() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <NavBarSignedIn />
      <Box
        sx={(theme) => ({
          [theme.breakpoints.up("xs")]: { height: "30px" },
          [theme.breakpoints.up("sm")]: { height: "35px" },
          [theme.breakpoints.up("md")]: { height: "40px" },
          [theme.breakpoints.up("lg")]: { height: "45px" },
          [theme.breakpoints.up("xl")]: { height: "50px" },
        })}
      ></Box>
      <Box>
        <Typography
          variant="h4"
          sx={{
            display: { xs: "none", md: "block" },
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          Dashboard
        </Typography>
      </Box>
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <ResourcesMenu />
            </Box>
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <BookmarksMenu />
            </Box>
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              flex: 1,
              position: "relative",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <ResourcesMenu />
          </Box>
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "40%",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <BookmarksMenu />
          </Box>
        </Box>
      </Toolbar>
      <MobileBottomNav />
    </Box>
  );
}

export default Dashboard;
