import NavBarSignedIn from "../../components/NavbarSignedIn";
import React, { useState, useEffect } from "react";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid2";
import MobileBottomNav from "../../components/MobileBottomNav";
import PreviewCard from "../../components/Projects/PreviewCard";
import { Project, fetchAllProjects } from "../../API/ProjectAPI";

function Projects() {
  let [allProjects, setProjects] = useState<Project[]>([]);

  useEffect(() => {
    const getData = async () => {
      try {
        const projectsData = await fetchAllProjects();
        setProjects(projectsData);
      } catch (error) {
        console.error(error);
      }
    };
    getData();
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <NavBarSignedIn />

      <Box
        sx={(theme) => ({
          [theme.breakpoints.up("xs")]: { height: "20px" },
          [theme.breakpoints.up("sm")]: { height: "25px" },
          [theme.breakpoints.up("md")]: { height: "30px" },
          [theme.breakpoints.up("lg")]: { height: "35px" },
          [theme.breakpoints.up("xl")]: { height: "40px" },
        })}
      ></Box>

      <Typography
        variant="h4"
        sx={{
          display: { xs: "none", md: "block" },
          Width: "100%",
          textAlign: "center",
          fontWeight: "bold",
        }}
      >
        Current Projects
      </Typography>

      <Box
        sx={{
          width: "90%",
          marginLeft: "5%",
          marginRight: "5%",
          display: "flex",
          flexDirection: "row",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
            flexDirection: "column",
            paddingBottom: "50px",
          }}
        >
          {allProjects &&
            allProjects.length > 0 &&
            allProjects.map((item) => <PreviewCard project={item} />)}
        </Box>
        <Box
          sx={{
            width: "100%",
            display: { xs: "none", md: "block" },
            marginLeft: "5%",
            marginRight: "5%",
            marginTop: "15px",
          }}
        >
          <Grid
            container
            rowSpacing={1}
            columnSpacing={0}
            sx={{
              width: "100%",
            }}
          >
            {allProjects &&
              allProjects.length > 0 &&
              allProjects.map((item) => (
                <Grid size={4}>
                  <PreviewCard project={item} />
                </Grid>
              ))}
          </Grid>
        </Box>
        <MobileBottomNav />
      </Box>
    </Box>
  );
}

export default Projects;
