// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Button from "@mui/material/Button";
import TableCell from "@mui/material/TableCell";
import TableRow from "@mui/material/TableRow";
import Link from "next/link";
import { ClickableTableRowProps } from "@/API/JSON";

export default function LinkMenuRow({
  hrefOrFunction,
  label,
  externalLink,
}: ClickableTableRowProps) {
  //goes in body tag, per autogenerated index.html file in public folder
  if (typeof hrefOrFunction != "string") {
    return (
      <TableRow
        sx={{
          "&:last-child td, &:last-child th": { border: 0 },
          backgroundColor: "#f7fbf9",
        }}
      >
        <TableCell
          sx={{
            width: "100%",
            height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
            padding: "0px",
          }}
        >
          <Button
            style={{
              width: "100%",
              height: "100%",
              padding: ".5em 1.5em .5em 1.5em",
              textDecoration: "none",
              textAlign: "center",
              textTransform: "none",
            }}
            onClick={() => {
              hrefOrFunction();
            }}
          >
            {label}
          </Button>
        </TableCell>
      </TableRow>
    );
  } else if (externalLink) {
    return (
      <TableRow
        sx={{
          "&:last-child td, &:last-child th": { border: 0 },
          backgroundColor: "#f7fbf9",
        }}
      >
        <TableCell
          sx={{
            width: "100%",
            height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
            padding: "0px",
          }}
        >
          <Button
            style={{
              width: "100%",
              height: "100%",
              padding: ".5em 1.5em .5em 1.5em",
              textDecoration: "none",
              textAlign: "center",
              textTransform: "none",
            }}
            href={hrefOrFunction}
          >
            {label}
          </Button>
        </TableCell>
      </TableRow>
    );
  } else {
    return (
      <TableRow
        sx={{
          "&:last-child td, &:last-child th": { border: 0 },
          backgroundColor: "#f7fbf9",
        }}
      >
        <TableCell
          sx={{
            width: "100%",
            height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
            padding: "0px",
          }}
        >
          <Link href={hrefOrFunction} passHref>
            <Button
              style={{
                width: "100%",
                height: "100%",
                padding: ".5em 1.5em .5em 1.5em",
                textDecoration: "none",
                textAlign: "center",
                textTransform: "none",
              }}
            >
              {label}
            </Button>
          </Link>
        </TableCell>
      </TableRow>
    );
  }
}
