// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import RescourcesTableRow from "@/components/LinkMenuRow";

interface ResourcesMenuProps {
  array: [string, string][];
  menuTitle: string;
}

export default function ResourcesMenu({
  array,
  menuTitle,
}: ResourcesMenuProps) {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250, maxWidth: 650 }} component={Paper}>
      <Table sx={{ minWidth: 250, maxWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                {menuTitle}
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {array.map((item, index) => (
            <RescourcesTableRow href={item[0]} label={item[1]} key={index} />
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}
