// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import { useRouter } from "next/navigation";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import { useBookmark } from "@/context/BookmarkContext";

export default function BookmarksMenu() {
  const { currBookmarkValues } = useBookmark();
  const router = useRouter();

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250, maxWidth: 650 }} component={Paper}>
      <Table sx={{ minWidth: 250, maxWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                Bookmarked Pages
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {currBookmarkValues.map((item, index) => (
            <TableRow
              sx={{
                "&:last-child td, &:last-child th": { border: 0 },
                backgroundColor: "#f7fbf9",
              }}
              key={index}
            >
              <TableCell>
                <Button
                  style={{
                    width: "100%",
                    padding: ".5em 1.5em .5em 1.5em",
                    textDecoration: "none",
                    textAlign: "center",
                  }}
                  onClick={() => router.push(item.link)}
                >
                  {item.label}
                </Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}
