// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import { useBookmark } from "@/context/BookmarkContext";
import Link from "next/link";
import Button from "@mui/material/Button";

export default function BookmarksMenu() {
  const { currBookmarkValues } = useBookmark();

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250, maxWidth: 650 }} component={Paper}>
      <Table sx={{ minWidth: 250, maxWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                Bookmarked Pages
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {currBookmarkValues.map((item, index) => (
            <TableRow
              sx={{
                "&:last-child td, &:last-child th": { border: 0 },
                backgroundColor: "#f7fbf9",
              }}
              key={index}
            >
              <TableCell
                sx={{
                  width: "100%",
                  height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                  padding: "0px",
                }}
              >
                {/* <LinkButton
                  href={item.link}
                  label={item.label}
                  width="100%"
                  height="100%"
                  padding=".5em 1.5em .5em 1.5em"
                  textDecoration="none"
                  textAlign="center"
                /> */}
                <Link href={item.link} passHref>
                  <Button
                    sx={{
                      width: "100%",
                      height: "100%",
                      padding: ".5em 1.5em .5em 1.5em",
                      textDecoration: "none",
                      textAlign: "center",
                      textTransform: "none",
                    }}
                  >
                    {item.label}
                  </Button>
                </Link>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}
