// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import RescourcesTableRow from "@/components/Dashboard/ResourcesTableRow";

function ResourcesMenu() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250, maxWidth: 650 }} component={Paper}>
      <Table sx={{ minWidth: 250, maxWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                4-H Resources
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h"
            label="4-H Youth Development"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/program/all/4h/events"
            label="Events"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/program/all/4h/local-programs"
            label="Local 4-H Program Finder"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h/about-4-h"
            label="About 4-H"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h/summer-camps"
            label="4-H Summer Camps"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h/projects"
            label="4-H Projects"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h/volunteer-training-manuals"
            label="Volunteer Resources"
          />
          <RescourcesTableRow
            href="https://extension.oregonstate.edu/4h/support-4-h"
            label="Support 4-H"
          />
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default ResourcesMenu;
