// Component adapted from: https://mui.com/material-ui/react-table/#system-BasicTable.js
import React from "react";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";

function ResourcesMenu() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <TableContainer sx={{ minWidth: 250, maxWidth: 650 }} component={Paper}>
      <Table sx={{ minWidth: 250, maxWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Typography
                variant="h6"
                style={{
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                4-H Resources
              </Typography>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h"
              >
                4-H Youth Development
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/program/all/4h/events"
              >
                Events
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/program/all/4h/local-programs"
              >
                Local 4-H Program Finder
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h/about-4-h"
              >
                About 4-H
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h/summer-camps"
              >
                4-H Summer Camps
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h/projects"
              >
                4-H Projects
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h/volunteer-training-manuals"
              >
                Volunteer Resources
              </Button>
            </TableCell>
          </TableRow>
          <TableRow
            sx={{
              "&:last-child td, &:last-child th": { border: 0 },
              backgroundColor: "#f7fbf9",
            }}
          >
            <TableCell
              sx={{
                width: "100%",
                height: { xs: "4em", s: "4em", md: "6.5em", lg: "4em" },
                padding: "0px",
              }}
            >
              <Button
                style={{
                  width: "100%",
                  height: "100%",
                  padding: ".5em 1.5em .5em 1.5em",
                  textDecoration: "none",
                  textAlign: "center",
                }}
                href="https://extension.oregonstate.edu/4h/support-4-h"
              >
                Support 4-H
              </Button>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default ResourcesMenu;
