"use client";

import React, { useState, useEffect } from "react";
import ResourcesMenu from "@/components/Dashboard/ResourcesMenu";
import BookmarksMenu from "@/components/Dashboard/BookmarksMenu";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";

function Dashboard() {
  const { currNavbarValues, updateFunction } = useNavbar();

  useEffect(() => {
    var navbarContextPageValues: NavbarValues = {
      mobileTitle: "Dashboard",
      desktopTitle: "4-H Record Books",
      hrefTitle: "/",
      mobileTopIcon: "none",
      NavbarLinks: navbarAppLinks,
      Bookmarks: currNavbarValues.Bookmarks,
    };

    updateFunction(navbarContextPageValues);
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Box>
        <Typography
          variant="h4"
          sx={{
            display: { xs: "none", md: "block" },
            Width: "100%",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          {currNavbarValues.mobileTitle}
        </Typography>
      </Box>
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <ResourcesMenu />
            </Box>
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <BookmarksMenu bookmarks={currNavbarValues.Bookmarks} />
            </Box>
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              flex: 1,
              position: "relative",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <ResourcesMenu />
          </Box>
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "40%",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <BookmarksMenu bookmarks={currNavbarValues.Bookmarks} />
          </Box>
        </Box>
      </Toolbar>
    </Box>
  );
}

export default Dashboard;
