"use client";

import React, { useEffect, useRef } from "react";
import MenuOfLinks from "@/components/MenuOfLinks";
import BookmarksMenu from "@/components/Dashboard/BookmarksMenu";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";

function Dashboard() {
  const { updateFunction } = useNavbar();
  const { updateBookmarks } = useBookmark();
  const hasRun = useRef(false);

  const externalResources: [string, string][] = [
    ["https://extension.oregonstate.edu/4h", "4-H Youth Development"],
    ["https://extension.oregonstate.edu/program/all/4h/events", "Events"],
    [
      "https://extension.oregonstate.edu/program/all/4h/local-programs",
      "Local 4-H Program Finder",
    ],
    ["https://extension.oregonstate.edu/4h/about-4-h", "About 4-H"],
    ["https://extension.oregonstate.edu/4h/summer-camps", "4-H Summer Camps"],
    ["https://extension.oregonstate.edu/4h/projects", "4-H Projects"],
    [
      "https://extension.oregonstate.edu/4h/volunteer-training-manuals",
      "Volunteer Resources",
    ],
    ["https://extension.oregonstate.edu/4h/support-4-h", "Support 4-H"],
  ];

  useEffect(() => {
    if (!hasRun.current) {
      const navbarContextPageValues: NavbarValues = {
        mobileTitle: "Dashboard",
        desktopTitle: "Dashboard",
        hrefTitle: "/Dashboard",
        mobileTopIcon: "none",
        NavbarLinks: navbarAppLinks,
      };
      updateFunction(navbarContextPageValues);

      // toggle to trigger bookmarks icon to check if page is bookmarked
      updateBookmarks(true);

      hasRun.current = true;
    }
  }, [updateFunction, updateBookmarks]);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <MenuOfLinks
                array={externalResources}
                menuTitle="4-H Resources"
              />
            </Box>
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <BookmarksMenu />
            </Box>
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              flex: 1,
              position: "relative",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <MenuOfLinks array={externalResources} menuTitle="4-H Resources" />
          </Box>
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "40%",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <BookmarksMenu />
          </Box>
        </Box>
      </Toolbar>
    </Box>
  );
}

export default Dashboard;
