"use client";

import React, { useEffect, useRef } from "react";
import MenuOfLinks from "@/components/MenuOfLinks";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import {
  useNavbar,
  NavbarValues,
  navbarAppLinks,
} from "@/context/NavbarContext";
import { useBookmark } from "@/context/BookmarkContext";
import { ClickableTableRowProps } from "@/API/JSON";

function Dashboard() {
  const { updateFunction } = useNavbar();
  const { updateBookmarks, currBookmarkValues } = useBookmark();
  const hasRun = useRef(false);

  const externalResources: ClickableTableRowProps[] = [
    {
      hrefOrFunction: "https://extension.oregonstate.edu/4h",
      label: "4-H Youth Development",
      externalLink: true,
    },
    {
      hrefOrFunction: "https://extension.oregonstate.edu/program/all/4h/events",
      label: "Events",
      externalLink: true,
    },
    {
      hrefOrFunction:
        "https://extension.oregonstate.edu/program/all/4h/local-programs",
      label: "Local 4-H Program Finder",
      externalLink: true,
    },
    {
      hrefOrFunction: "https://extension.oregonstate.edu/4h/about-4-h",
      label: "About 4-H",
      externalLink: true,
    },
    {
      hrefOrFunction: "https://extension.oregonstate.edu/4h/summer-camps",
      label: "4-H Summer Camps",
      externalLink: true,
    },
    {
      hrefOrFunction: "https://extension.oregonstate.edu/4h/projects",
      label: "4-H Projects",
      externalLink: true,
    },
    {
      hrefOrFunction:
        "https://extension.oregonstate.edu/4h/volunteer-training-manuals",
      label: "Volunteer Resources",
      externalLink: true,
    },
    {
      hrefOrFunction: "https://extension.oregonstate.edu/4h/support-4-h",
      label: "Support 4-H",
      externalLink: true,
    },
  ];

  useEffect(() => {
    if (!hasRun.current) {
      const navbarContextPageValues: NavbarValues = {
        mobileTitle: "Dashboard",
        desktopTitle: "Dashboard",
        hrefTitle: "/Dashboard",
        NavbarLinks: navbarAppLinks,
      };
      updateFunction(navbarContextPageValues);

      // toggle to trigger bookmarks icon to check if page is bookmarked
      updateBookmarks(true);

      hasRun.current = true;
    }
  }, [updateFunction, updateBookmarks]);

  const bookmarksModifiedArray: ClickableTableRowProps[] =
    currBookmarkValues.map((bookmark) => ({
      hrefOrFunction: bookmark.link,
      label: bookmark.label,
      externalLink: false,
    }));

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <Toolbar
        disableGutters
        sx={{
          display: { xs: "flex" },
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "flex", md: "none" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: "100%",
            }}
          >
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <MenuOfLinks
                array={externalResources}
                menuTitle="4-H Resources"
              />
            </Box>
            <Box
              sx={{
                flex: 1,
                position: "relative",
                padding: "20px",
                Width: "80%",
                paddingLeft: "10%",
                paddingRight: "10%",
                paddingBottom: "50px",
              }}
            >
              <MenuOfLinks
                array={bookmarksModifiedArray}
                menuTitle="Bookmarks"
              />
            </Box>
          </Box>
        </Box>
        <Box
          sx={{
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            width: "100%",
          }}
        >
          <Box
            sx={{
              flex: 1,
              position: "relative",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <MenuOfLinks array={externalResources} menuTitle="4-H Resources" />
          </Box>
          <Box
            sx={{
              flex: 1,
              position: "relative",
              Width: "40%",
              paddingLeft: "5%",
              paddingRight: "5%",
              paddingTop: "15px",
            }}
          >
            <MenuOfLinks array={bookmarksModifiedArray} menuTitle="Bookmarks" />
          </Box>
        </Box>
      </Toolbar>
    </Box>
  );
}

export default Dashboard;
