import React from "react";
import NavBarError from "../components/NavbarError";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";

export default function FourZeroFour() {
  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <NavBarError />
      <Box
        sx={(theme) => ({
          [theme.breakpoints.up("xs")]: { height: "20px" },
          [theme.breakpoints.up("sm")]: { height: "25px" },
          [theme.breakpoints.up("md")]: { height: "30px" },
          [theme.breakpoints.up("lg")]: { height: "35px" },
          [theme.breakpoints.up("xl")]: { height: "40px" },
        })}
      ></Box>
      <Typography variant="h1" sx={{ width: "100%", textAlign: "center" }}>
        404
      </Typography>
      <Typography variant="h2" sx={{ width: "100%", textAlign: "center" }}>
        This page could not be found.
      </Typography>
    </Box>
  );
}
