import NavBarLanding from "../components/NavbarLanding";
import React, { useState, useEffect } from "react";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";
import Container from "@mui/material/Container";
import Button from "@mui/material/Button";

function DummySignOn() {
  // function to get all projects below
  let [allProjects, setProjects] = useState(null);

  useEffect(() => {
    console.log(`${process.env.NEXT_PUBLIC_API_URL}/signin`);
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/signin`, {
      method: "POST",
      headers: {
        "Content-Type": "text/plain", // Or 'application/xml', 'application/octet-stream', etc.
      },
      body: '{"id": "1"}',
      console.log("Response status code:", response.status);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    });
  }, []);

  //goes in body tag, per autogenerated index.html file in public folder
  return (
    <Box className="App">
      <NavBarLanding />
      <Box
        sx={(theme) => ({
          [theme.breakpoints.up("xs")]: { height: "30px" },
          [theme.breakpoints.up("sm")]: { height: "35px" },
          [theme.breakpoints.up("md")]: { height: "40px" },
          [theme.breakpoints.up("lg")]: { height: "45px" },
          [theme.breakpoints.up("xl")]: { height: "50px" },
        })}
      ></Box>
      <Typography
        variant="h4"
        sx={{
          Width: "100%",
          textAlign: "center",
          fontWeight: "bold",
          marginBotton: "20px",
        }}
      >
        Dummy Sign On Page (Placeholder)
      </Typography>

      <Button
        variant="contained"
        href="/Dashboard"
        sx={{
          width: "30%",
          marginLeft: "35%",
          marginRight: "35%",
          marginTop: "10%",
        }}
      >
        To Signed On Pages{" "}
      </Button>
    </Box>
  );
}

export default DummySignOn;
